import type { Metadata } from "next";
import "./globals.css";

import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="flex flex-col gap-6 justify-center text-center">
          <h1 className="text-5xl font-bold">Market Mayhem</h1>
          <nav className="flex justify-center gap-48">
            <Link
              href="/market"
              className="bg-blue-500 rounded p-2 text-white hover:text-yellow-300"
            >
              Stock Market
            </Link>
            <Link
              href="/dashboard"
              className="bg-blue-500 rounded p-2 text-white hover:text-yellow-300"
            >
              Dashboard
            </Link>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
